process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = 'my-super-secret-local-key';
process.env.DATABASE_URL = 'postgresql://postgres:postgres123@localhost:5445/nexacommerce_db?schema=payment_test';
process.env.PORT = '3006';
process.env.RABBITMQ_URL = 'amqp://guest:guest@localhost:5672';
process.env.MIDTRANS_SERVER_KEY = 'SB-Mid-server-test';
process.env.MIDTRANS_CLIENT_KEY = 'SB-Mid-client-test';
process.env.MIDTRANS_MERCHANT_ID = 'test-merchant';
process.env.MIDTRANS_IS_PRODUCTION = 'false';
