process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = 'my-super-secret-local-key';
process.env.DATABASE_URL ??= 'postgresql://postgres:postgres123@localhost:5445/nexacommerce_db?schema=analytics_test';
process.env.PORT = '3012';
process.env.RABBITMQ_URL = 'amqp://guest:guest@localhost:5672';
process.env.AUTH_SERVICE_URL = 'http://localhost:3001';
process.env.PRODUCT_SERVICE_URL = 'http://localhost:3003';
process.env.ORDER_SERVICE_URL = 'http://localhost:3005';
process.env.REVIEW_SERVICE_URL = 'http://localhost:3010';
